/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pokedex;

import java.awt.Image;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author Andres
 */
public class PokeDexGui extends javax.swing.JFrame 
{
ArrayList<PokeDex> PokemonInfo = new ArrayList<>();
    /**
     * Creates new form PokeDexGui
     */
    public PokeDexGui() 
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jSpinnerNumber = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelHeight = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelWeight = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBio = new javax.swing.JTextArea();
        jLabelPokemonDisplay = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelAbilityOne = new javax.swing.JLabel();
        jLabelAbilityTwo = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabelTypeTwo = new javax.swing.JLabel();
        jLabelTypeOne = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(677, 790));
        setPreferredSize(new java.awt.Dimension(677, 830));
        setSize(new java.awt.Dimension(677, 790));
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/Pokemon Number Img.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 13, 141, 22);

        jSpinnerNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, 151, 1));
        jSpinnerNumber.setFocusCycleRoot(true);
        jSpinnerNumber.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                jSpinnerNumberStateChanged(evt);
            }
        });
        getContentPane().add(jSpinnerNumber);
        jSpinnerNumber.setBounds(58, 53, 47, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/Name Img.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(58, 93, 45, 22);

        jLabelName.setBackground(new java.awt.Color(255, 255, 255));
        jLabelName.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabelName.setOpaque(true);
        getContentPane().add(jLabelName);
        jLabelName.setBounds(12, 143, 141, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/Height Img.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(57, 183, 51, 22);

        jLabelHeight.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHeight.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabelHeight.setOpaque(true);
        getContentPane().add(jLabelHeight);
        jLabelHeight.setBounds(12, 223, 141, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/Weight Img.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(56, 263, 55, 22);

        jLabelWeight.setBackground(new java.awt.Color(255, 255, 255));
        jLabelWeight.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabelWeight.setOpaque(true);
        getContentPane().add(jLabelWeight);
        jLabelWeight.setBounds(12, 303, 141, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/Bio Img.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(12, 596, 25, 22);

        jTextAreaBio.setEditable(false);
        jTextAreaBio.setColumns(20);
        jTextAreaBio.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jTextAreaBio.setLineWrap(true);
        jTextAreaBio.setRows(5);
        jTextAreaBio.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaBio);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(12, 636, 634, 140);

        jLabelPokemonDisplay.setPreferredSize(new java.awt.Dimension(475, 475));
        getContentPane().add(jLabelPokemonDisplay);
        jLabelPokemonDisplay.setBounds(171, 143, 475, 475);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/Abilities Img.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(55, 343, 56, 22);

        jLabelAbilityOne.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAbilityOne.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabelAbilityOne.setOpaque(true);
        getContentPane().add(jLabelAbilityOne);
        jLabelAbilityOne.setBounds(12, 383, 141, 22);

        jLabelAbilityTwo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAbilityTwo.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
        jLabelAbilityTwo.setOpaque(true);
        getContentPane().add(jLabelAbilityTwo);
        jLabelAbilityTwo.setBounds(12, 423, 141, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/Type Img.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(171, 53, 39, 22);

        jLabelTypeTwo.setPreferredSize(new java.awt.Dimension(100, 112));
        getContentPane().add(jLabelTypeTwo);
        jLabelTypeTwo.setBounds(356, 13, 100, 112);

        jLabelTypeOne.setPreferredSize(new java.awt.Dimension(100, 112));
        getContentPane().add(jLabelTypeOne);
        jLabelTypeOne.setBounds(238, 13, 100, 112);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Label Images/BackGround Img.png"))); // NOI18N
        jLabel8.setText("Region");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 680, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerNumberStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerNumberStateChanged
        for(PokeDex p : PokemonInfo)
        {
            if((int) jSpinnerNumber.getValue() == p.getNumber())
            {
                jLabelName.setText(p.getName());
                jLabelHeight.setText(p.getHeight());
                jLabelWeight.setText(p.getWeight());
                jTextAreaBio.setText(p.getBiography());
                
                Image pokemonImg = new ImageIcon(getClass().getResource("/Images/" + Integer.toString((int) jSpinnerNumber.getValue()) + ".png")).getImage();
                jLabelPokemonDisplay.setIcon(new ImageIcon(pokemonImg));
                
                Image pokemonTypeOneImg = new ImageIcon(getClass().getResource("/TypeImages/" +  p.getTypeOne() + ".png")).getImage();
                jLabelTypeOne.setIcon(new ImageIcon(pokemonTypeOneImg));
                
                if(!p.getTypeTwo().equals("None"))
                {
                  jLabelTypeTwo.setVisible(true);
                  Image pokemonTypeTwoImg = new ImageIcon(getClass().getResource("/TypeImages/" + p.getTypeTwo() + ".png")).getImage();  
                  jLabelTypeTwo.setIcon(new ImageIcon(pokemonTypeTwoImg));
                }
                
                else
                {
                    jLabelTypeTwo.setVisible(false);
                }
                
                jLabelAbilityOne.setText(p.getAbility());
                
                if(p.getAbilityTwo().equals("None"))
                {
                    jLabelAbilityTwo.setText("");
                }
                else
                    jLabelAbilityTwo.setText(p.getAbilityTwo());
            }
        }
    }//GEN-LAST:event_jSpinnerNumberStateChanged

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try 
        {
           FileReader fileReader = new FileReader("Pokemon.txt");
           Scanner scanner = new Scanner(fileReader);
           while(scanner.hasNextLine())
           {
               String curLine = scanner.nextLine();
               String pokemonInfo[] = curLine.split("\t");
               PokeDex p = new PokeDex(Integer.parseInt(pokemonInfo[0]), pokemonInfo[1], pokemonInfo[2], pokemonInfo[3], pokemonInfo[4], pokemonInfo[5], pokemonInfo[6], pokemonInfo[7], pokemonInfo[8]);
               PokemonInfo.add(p);
           }
        } 
        catch (FileNotFoundException ex) 
        {
            Logger.getLogger(PokeDexGui.class.getName()).log(Level.SEVERE, null, ex);
        } 
                
        for(PokeDex p : PokemonInfo)
        {
            if((int) jSpinnerNumber.getValue() == p.getNumber())
            {
                jLabelName.setText(p.getName());
                jLabelHeight.setText(p.getHeight());
                jLabelWeight.setText(p.getWeight());
                jTextAreaBio.setText(p.getBiography());
                
                Image pokemonImg = new ImageIcon(getClass().getResource("/Images/" + Integer.toString((int) jSpinnerNumber.getValue()) + ".png")).getImage();
                jLabelPokemonDisplay.setIcon(new ImageIcon(pokemonImg));
                
                Image pokemonTypeOneImg = new ImageIcon(getClass().getResource("/TypeImages/" +  p.getTypeOne() + ".png")).getImage();
                jLabelTypeOne.setIcon(new ImageIcon(pokemonTypeOneImg));
                
                if(!p.getTypeTwo().equals("None"))
                {
                  jLabelTypeTwo.setVisible(true);
                  Image pokemonTypeTwoImg = new ImageIcon(getClass().getResource("/TypeImages/" + p.getTypeTwo() + ".png")).getImage();  
                  jLabelTypeTwo.setIcon(new ImageIcon(pokemonTypeTwoImg));
                }
                
                else
                {
                    jLabelTypeTwo.setVisible(false);
                }
                
                jLabelAbilityOne.setText(p.getAbility());
                
                if(p.getAbilityTwo().equals("None"))
                {
                    jLabelAbilityTwo.setText("");
                }
                else
                    jLabelAbilityTwo.setText(p.getAbilityTwo());
            }
        } 
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PokeDexGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PokeDexGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PokeDexGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PokeDexGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PokeDexGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelAbilityOne;
    private javax.swing.JLabel jLabelAbilityTwo;
    private javax.swing.JLabel jLabelHeight;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelPokemonDisplay;
    private javax.swing.JLabel jLabelTypeOne;
    private javax.swing.JLabel jLabelTypeTwo;
    private javax.swing.JLabel jLabelWeight;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinnerNumber;
    private javax.swing.JTextArea jTextAreaBio;
    // End of variables declaration//GEN-END:variables
}
